image: golang:latest

stages:
  - prep
  - build

vet:
  script:
    - make vet
  stage: prep
  tags:
    - go

build:
  script:
    - export VERSION=$CI_BUILD_REF_NAME-$CI_BUILD_REF
    - make build
  stage: build
  tags:
    - go
  except:
    - tags

release-386:
  script:
    - export VERSION=$CI_BUILD_TAG
    - export ARCH=386
    - make release
  stage: build
  tags:
    - go
  artifacts:
    name: "coyote-386-$CI_BUILD_TAG"
    paths:
    - build/*
  only:
    - tags

release-arm:
  script:
    - export VERSION=$CI_BUILD_TAG
    - export ARCH=arm
    - make release
  stage: build
  tags:
    - go
  artifacts:
    name: "coyote-arm-$CI_BUILD_TAG"
    paths:
    - build/*
  only:
    - tags

release-amd64:
  script:
    - export VERSION=$CI_BUILD_TAG
    - export ARCH=amd64
    - make release
  stage: build
  tags:
    - go
  artifacts:
    name: "coyote-amd64-$CI_BUILD_TAG"
    paths:
    - build/*
  only:
    - tags
