image: golang:1.7

variables:
  SCM_DOMAIN: "git.magnax.ca"

before_script:
  - mkdir -p "$GOPATH/src/$SCM_DOMAIN/$CI_PROJECT_NAMESPACE"
  - ln -s "$CI_PROJECT_DIR" "$GOPATH/src/$SCM_DOMAIN/$CI_PROJECT_PATH"
  - cd "$GOPATH/src/$SCM_DOMAIN/$CI_PROJECT_PATH"

stages:
  - prep
  - build

vet:
  script:
    - make vet
  stage: prep
  tags:
    - go

.build: &build
  script:
    - make build
  stage: build
  tags:
    - go
  except:
    - tags

build:1.5:
  <<: *build
  image: golang:1.5
  script:
    - export GO15VENDOREXPERIMENT=1
    - make build

build:1.6:
  <<: *build
  image: golang:1.6

build:1.7:
  <<: *build
  image: golang:1.7

.release: &release
  stage: build
  tags:
    - go
  artifacts:
    paths:
      - build/*
  only:
    - tags

release-386:
  <<: *release
  script:
    - export BUILD_ARCH=386
    - export BUILD_VERSION=$(git describe)
    - make release
  artifacts:
    name: "coyote-386-$CI_BUILD_TAG"

release-amd64:
  <<: *release
  script:
    - export BUILD_ARCH=amd64
    - export BUILD_VERSION=$(git describe)
    - make release
  artifacts:
    name: "coyote-amd64-$CI_BUILD_TAG"

release-arm:
  <<: *release
  script:
    - export BUILD_ARCH=arm
    - export BUILD_VERSION=$(git describe)
    - make release
  artifacts:
    name: "coyote-arm-$CI_BUILD_TAG"

release-arm64:
  <<: *release
  script:
    - export BUILD_ARCH=arm64
    - export BUILD_VERSION=$(git describe)
    - make release
  artifacts:
    name: "coyote-arm64-$CI_BUILD_TAG"
