image: golang:1.6

before_script:
  - mkdir -p "$GOPATH/src/git.magnax.ca/$CI_PROJECT_NAMESPACE"
  - ln -s "$CI_PROJECT_DIR" "$GOPATH/src/git.magnax.ca/$CI_PROJECT_PATH"
  - cd "$GOPATH/src/git.magnax.ca/$CI_PROJECT_PATH"

stages:
  - prep
  - build

vet:
  script:
    - make vet
  stage: prep
  tags:
    - go

build:
  script:
    - make build
  stage: build
  tags:
    - go
  except:
    - tags

.release: &release
  stage: build
  before_script:
    - export BUILD_VERSION=$(git describe)
  tags:
    - go
  artifacts:
    paths:
      - build/*
  only:
    - tags

release-386:
  <<: *release
  script:
    - export BUILD_ARCH=386
    - make release
  artifacts:
    name: "coyote-386-$CI_BUILD_TAG"

release-arm:
  <<: *release
  script:
    - export BUILD_ARCH=arm
    - make release
  artifacts:
    name: "coyote-arm-$CI_BUILD_TAG"

release-arm64:
  <<: *release
  script:
    - export BUILD_ARCH=arm64
    - make release
  artifacts:
    name: "coyote-arm64-$CI_BUILD_TAG"

release-amd64:
  <<: *release
  script:
    - export BUILD_ARCH=amd64
    - make release
  artifacts:
    name: "coyote-amd64-$CI_BUILD_TAG"
