image: golang:1.11s

stages:
  - prep
  - build

vet:
  script:
    - make vet
  stage: prep
  tags:
    - go

build:
  script:
    - make build
  stage: build
  tags:
    - go
  except:
    - tags

.release: &release
  stage: build
  tags:
    - go
  only:
    - tags

release-386:
  <<: *release
  script:
    - export BUILD_ARCH=386
    - export BUILD_VERSION=$(git describe)
    - make release
  artifacts:
    name: "coyote-386-$CI_BUILD_TAG"
    paths:
      - build/*

release-amd64:
  <<: *release
  script:
    - export BUILD_ARCH=amd64
    - export BUILD_VERSION=$(git describe)
    - make release
  artifacts:
    name: "coyote-amd64-$CI_BUILD_TAG"
    paths:
      - build/*

release-arm:
  <<: *release
  script:
    - export BUILD_ARCH=arm
    - export BUILD_VERSION=$(git describe)
    - make release
  artifacts:
    name: "coyote-arm-$CI_BUILD_TAG"
    paths:
      - build/*
